### ISSUE TITLE
incompatible with ppx_deriving_yojson > 3.0

### ISSUE THREAD

**Issue by avsm** [bataille/ocaml-transmission-rpc#1]
The latest verson of ppx_deriving_yojson has changed the type of `result` to use the upstream  `Result.result` instead of polymorphic variants.

This means that the following type error happens if compiled with the latest one:

```
- File "lib/answer.ml", line 231, characters 24-38:
- Error: This expression has type
-          Yojson.Safe.json -> file Ppx_deriving_yojson_runtime.error_or
-        but an expression was expected of type
-          Yojson.Safe.json -> ([< `Error of 'b | `Ok of 'c ] as 'a)
-        Type file Ppx_deriving_yojson_runtime.error_or = (file, string) result
-        is not compatible with type [< `Error of 'b | `Ok of 'c ] as 'a 
- Command exited with code 2.
```

**Comment by bataille** [comment]
Thank you for the report.
I converted the part of the code using the polymorphic variants to using Result.result.
I will submit the change to opam when I will have tested it more thoroughly.
